import { Title } from '@Components/atoms/Title'
import { Slider } from '@Components/molecules/Slider'

export const HomePage = () => {
  const slides = [
    <div
      key="slide1"
      style={{
        background: 'red',
        height: '200px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}
    >
      Slide 1
    </div>,
    <div
      key="slide2"
      style={{
        background: 'blue',
        height: '200px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}
    >
      Slide 2
    </div>,
    <div
      key="slide3"
      style={{
        background: 'green',
        height: '200px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}
    >
      Slide 3
    </div>
  ]

  return (
    <>
      <div style={{ height: '100vh' }}>
        <Title variant="h1">Home Page</Title>
        <p>Generated by create next app</p>
        <Slider
          slides={slides}
          orientation="vertical"
          animationType="slide"
          showControls={true}
          slidesPerView={1}
        />
      </div>
      <div style={{ height: '100vh' }}>
        <Title variant="h1">Home Page</Title>
        <p>Generated by create next app</p>
      </div>
    </>
  )
}
