import { Title } from '@Components/atoms/Title'
import { Slider } from '@Components/molecules/Slider'

export const HomePage = () => {
  const slides = [
    <div
      key="slide1"
      style={{
        background: 'red',
        height: '100dvh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}
    >
      Slide 1
    </div>
  ]

  return (
    <>
      <div style={{ height: '100vh' }}>
        <Slider
          slides={slides}
          options={{
            animationType: 'fade',
            showControls: true,
            slidesPerView: 1,
            slidesToScroll: 'auto',
            loop: true,
            autoHeight: false,
            active: true
          }}
        />
      </div>
      <div style={{ height: '100vh' }}>
        <Title variant="h1">Home Page</Title>
        <p>Generated by create next app</p>
      </div>
    </>
  )
}
