import { Title } from '@Components/atoms/Title'

export const HomePage = () => {
  return (
    <div style={{ height: '100vh' }}>
      <Title variant="h1">Home Page</Title>
      <p>Generated by create next app</p>
    </div>
  )
}
