export const WEB_SITES = 'websites'
export const ECOMMERCE = 'ecommerce'
export const CUSTOM_SOFTWARE = 'custom-software'
export const MOBILE_APPS = 'mobile-apps'
export const LANDING_PAGES = 'landing-pages'
export const UI_UX_DESIGN = 'ui-ux-design'
export const SEO_SEM = 'seo-sem'
export const EMAIL_MARKETING = 'email-marketing'
