#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# echo "Running lint-staged..."
# npx lint-staged

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format || (
	echo '🚨Prettier Check Failed🚨 Make the required changes listed above, add changes and try to commit again.'
  false;
)

echo '✅ Prettier Check Passed'

# Check ESLint Standards
npm run check-lint ||
(
	echo '🚨Eslint Check Failed🚨 Make the required changes listed above, add changes and try to commit again.'
	false;
)

echo '✅ Eslint Check Passed'

# Check tsconfig standards
npm run check-types ||
(
	echo '🚨Typescript Check Failed🚨 Make the required changes listed above, add changes and try to commit again.'
	false;
)

echo '✅ Typescript Check Passed'


npm run build ||
(
	echo '🚨Build Check Failed🚨 Make the required changes listed above, add changes and try to commit again.'
	false;
)

# If everything passes... Now we can commit
echo '✅ Build Check Passed, now we can git commit 📄'
