#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# echo "Running lint-staged..."
# npx lint-staged
echo ''
echo '===================================='
echo '🔄️ Start checks before commiting...'
echo '⬜ Prettier'
echo '⬜ Next/Eslint'
echo '⬜ Typescript'
echo '===================================='

# Check Prettier standards
npm run check-format || (
	echo '🚨Prettier Check Failed🚨 Make the required changes listed above, add changes and try to commit again.'
  false
)

echo ''
echo '===================================='
echo '✅ Prettier (Check Passed)'
echo '⬜ Next/Eslint'
echo '⬜ Typescript'
echo '===================================='

# Check Next/ESLint Standards
npm run lint ||
(
	echo '🚨Eslint Check Failed🚨 Make the required changes listed above, add changes and try to commit again.'
	false
)

echo ''
echo '===================================='
echo '✅ Prettier (Check Passed)'
echo '✅ Next/Eslint (Check Passed)'
echo '⬜ Typescript'
echo '===================================='

# Check tsconfig standards
npm run check-types ||
(
	echo '🚨Typescript Check Failed🚨 Make the required changes listed above, add changes and try to commit again.'
	false
)

echo ''
echo '===================================='
echo '✅ Prettier (Check Passed)'
echo '✅ Next/Eslint (Check Passed)'
echo '✅ Typescript (Check Passed)'
echo '===================================='


echo ''
echo 'Now we can git commit 📄'
echo ''

echo '===================================='
echo '🚀 Ready to git push?'
echo '===================================='
echo ''
