name: 🚀 Deploy to Vercel

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  deploy:
    name: Deploy Preview/Staging/Production
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v4
        with:
          version: 9.15.0

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🚀 Deploy to Vercel
        uses: amondnet/vercel-action@4b001a441d80e00aeed3680a3719d1d8b95998c5 # v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
